#!/bin/bash
# case example
case $1 in
install)
pkg install $2
;;
reset)
reset
;;
id)
whoami
;;
user)
whoami
;;
getpid)
top
;;
pwd)
pwd
;;
uninstall)
pkg uninstall $2
;;
delete)
rm -rf $2
echo $2 deleted
;;
add)
sh /data/data/com.termux/files/usr/var/Friday.exc/add
;;
sub)
sh /data/data/com.termux/files/usr/var/Friday.exc/sub
;;
multi)
sh /data/data/com.termux/files/usr/var/Friday.exc/mult
;;
div)
sh /data/data/com.termux/files/usr/var/Friday.exc/div
;;
info)
sh /data/data/com.termux/files/usr/var/Friday.exc/logo
;;
oddeve)
sh /data/data/com.termux/files/usr/var/Friday.exc/oddeve
;;
text-info)
wc $2
echo "line ,word ,chracter"
;;
unzip)
unzip $2
;;
download)
wget $2
;;
free-ram)
free -h -t
;;
torch)
termux-torch $2
;;
speak)
espeak $2
;;
battery)
termux-battery-$2
;;
camera)
termux-camera-$2
;;
enable)
termux-$2-enable true
;;
disable)
termux-$2-enable false
;;
scan)
termux-$2-scaninfo
;;
vibrate)
termux-vibrate
;;
weather)
sh /data/data/com.termux/files/usr/var/Friday.exc/weather
;;
device)
echo $2
neofetch
;;
logout)
exit
exit
exit
sleep 1
;;
fingerprint)
termux-fingerprint
;;
capture)
slerp 1
termux-camera-photo
;;
auto)
pkg $2 -y
pkg updrade -y
pip install --upgrade pip
;;
help)

printf '\033[36m';echo "install <packageName>"
printf '\033[36m';echo "unistall <packageNam>"
printf '\033[36m';echo "reset   to reset terminal"
echo "info  to see information about Friday"
echo "device info   to see device info"
echo "id   to get user name"
echo "user   to get user name"
echo "delete file/folder  to delete file/folder"
echo "getpid  to get pid of process"
echo "pwd   to pwd"
echo "add  to do addition "
echo "sub  to do  subtraction"
echo "multi  to do multiply"
echo "download <link>  to download file from that link"
printf '\033[36m';echo "div   to divide"
echo "oddeve   to find a number is odd or eve"
printf '\033[36m';echo "text-info <fileName>   to show number of line,word ,character in a file"
echo "unzip <fileName>   to unzip file"
echo "weather  to dislay weather"
echo "enable wifi  to enable wifi"
echo "disable wifi to disable wifi"
echo "scan wifi   to show avalable wifi"
echo "vibrate  to vibrate"
echo "auto update to auto update"
echo "speak <word>  to speak a word"
echo "fingerprint  Use fingerprint sensor on device to check for authentication" 
printf '\033[36m';echo "free-ram  to free ram"
echo "tourch on/off   to turn tourch on/off"
echo "batter status  to show battery info/status"
echo "camera info  to print camera information"
echo "capture  to take a photo"
echo "help  to show this text"
echo ""
printf '\033[33m';echo "If any command  is not working make a issue in  github"
;;
*)
printf '\033[36m';echo "I don\'t know, if you want that command made a pull request ,or tell in discussion page."
;;
esac
